// AR Asset seed data
// Each entry references a product or hairstyle by name (looked up at seed time)

type ArAssetSeed = {
  productName?: string;
  hairstyleName?: string;
  assetType: string;
  modelUrl: string;
  textureUrl: string | null;
  thumbnailUrl: string | null;
  anchorPoint: string;
  blendMode: string | null;
  opacity: number;
  scale: { x: number; y: number; z: number };
  offset: { x: number; y: number; z: number };
  metadata: Record<string, unknown> | null;
  version: number;
  fileSizeBytes: number;
};

export const arAssets: ArAssetSeed[] = [
  // ═══════════════════════════════════════════════════════════
  // MAKEUP_OVERLAY - Foundations (full_face)
  // ═══════════════════════════════════════════════════════════
  {
    productName: 'Sand Foundation',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/sand-foundation.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/sand-foundation-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/sand-foundation.png',
    anchorPoint: 'full_face',
    blendMode: 'multiply',
    opacity: 0.35,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { colorSpace: 'sRGB', premultipliedAlpha: true },
    version: 1,
    fileSizeBytes: 245_000,
  },
  {
    productName: 'Porcelain Glow Foundation',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/porcelain-glow-foundation.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/porcelain-glow-foundation-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/porcelain-glow-foundation.png',
    anchorPoint: 'full_face',
    blendMode: 'multiply',
    opacity: 0.3,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { colorSpace: 'sRGB', premultipliedAlpha: true },
    version: 1,
    fileSizeBytes: 238_000,
  },
  {
    productName: 'Chestnut Foundation',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/chestnut-foundation.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/chestnut-foundation-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/chestnut-foundation.png',
    anchorPoint: 'full_face',
    blendMode: 'multiply',
    opacity: 0.4,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { colorSpace: 'sRGB', premultipliedAlpha: true },
    version: 1,
    fileSizeBytes: 252_000,
  },

  // ═══════════════════════════════════════════════════════════
  // MAKEUP_OVERLAY - Blush (left_cheek / right_cheek)
  // ═══════════════════════════════════════════════════════════
  {
    productName: 'Rose Petal Blush',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/rose-petal-blush.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/rose-petal-blush-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/rose-petal-blush.png',
    anchorPoint: 'left_cheek',
    blendMode: 'overlay',
    opacity: 0.55,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { mirrorToRightCheek: true },
    version: 1,
    fileSizeBytes: 128_000,
  },
  {
    productName: 'Coral Reef Blush',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/coral-reef-blush.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/coral-reef-blush-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/coral-reef-blush.png',
    anchorPoint: 'right_cheek',
    blendMode: 'overlay',
    opacity: 0.5,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { mirrorToLeftCheek: true },
    version: 1,
    fileSizeBytes: 132_000,
  },
  {
    productName: 'Strawberry Cream Blush',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/strawberry-cream-blush.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/strawberry-cream-blush-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/strawberry-cream-blush.png',
    anchorPoint: 'left_cheek',
    blendMode: 'overlay',
    opacity: 0.6,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { mirrorToRightCheek: true, dewyEffect: true },
    version: 1,
    fileSizeBytes: 141_000,
  },

  // ═══════════════════════════════════════════════════════════
  // MAKEUP_OVERLAY - Eyeshadow (left_eye / right_eye)
  // ═══════════════════════════════════════════════════════════
  {
    productName: 'Champagne Toast Shadow',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/champagne-toast-shadow.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/champagne-toast-shadow-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/champagne-toast-shadow.png',
    anchorPoint: 'left_eye',
    blendMode: 'screen',
    opacity: 0.65,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: -2, z: 0 },
    metadata: { mirrorToRightEye: true, shimmerIntensity: 0.4 },
    version: 1,
    fileSizeBytes: 98_000,
  },
  {
    productName: 'Soft Taupe Shadow',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/soft-taupe-shadow.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/soft-taupe-shadow-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/soft-taupe-shadow.png',
    anchorPoint: 'right_eye',
    blendMode: 'multiply',
    opacity: 0.6,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: -2, z: 0 },
    metadata: { mirrorToLeftEye: true },
    version: 1,
    fileSizeBytes: 92_000,
  },
  {
    productName: 'Plum Velvet Shadow',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/plum-velvet-shadow.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/plum-velvet-shadow-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/plum-velvet-shadow.png',
    anchorPoint: 'left_eye',
    blendMode: 'multiply',
    opacity: 0.7,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: -2, z: 0 },
    metadata: { mirrorToRightEye: true },
    version: 1,
    fileSizeBytes: 105_000,
  },
  {
    productName: 'Bronze Goddess Shadow',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/bronze-goddess-shadow.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/bronze-goddess-shadow-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/bronze-goddess-shadow.png',
    anchorPoint: 'right_eye',
    blendMode: 'screen',
    opacity: 0.65,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: -2, z: 0 },
    metadata: { mirrorToLeftEye: true, metallicIntensity: 0.6 },
    version: 1,
    fileSizeBytes: 110_000,
  },

  // ═══════════════════════════════════════════════════════════
  // MAKEUP_OVERLAY - Lipstick (lips)
  // ═══════════════════════════════════════════════════════════
  {
    productName: 'Classic Red Lipstick',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/classic-red-lipstick.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/classic-red-lipstick-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/classic-red-lipstick.png',
    anchorPoint: 'lips',
    blendMode: 'overlay',
    opacity: 0.8,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { finishType: 'satin', lipSegmentation: true },
    version: 1,
    fileSizeBytes: 85_000,
  },
  {
    productName: 'Bare Nude Lipstick',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/bare-nude-lipstick.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/bare-nude-lipstick-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/bare-nude-lipstick.png',
    anchorPoint: 'lips',
    blendMode: 'overlay',
    opacity: 0.6,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { finishType: 'satin', lipSegmentation: true },
    version: 1,
    fileSizeBytes: 82_000,
  },
  {
    productName: 'Berry Lipstick',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/berry-lipstick.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/berry-lipstick-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/berry-lipstick.png',
    anchorPoint: 'lips',
    blendMode: 'overlay',
    opacity: 0.75,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { finishType: 'satin', lipSegmentation: true },
    version: 1,
    fileSizeBytes: 88_000,
  },

  // ═══════════════════════════════════════════════════════════
  // MAKEUP_OVERLAY - Highlighter (forehead / cheekbones)
  // ═══════════════════════════════════════════════════════════
  {
    productName: 'Champagne Pop',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/champagne-pop-highlight.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/champagne-pop-highlight-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/champagne-pop-highlight.png',
    anchorPoint: 'forehead',
    blendMode: 'screen',
    opacity: 0.45,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { applyToHighPoints: true, shimmerIntensity: 0.7 },
    version: 1,
    fileSizeBytes: 115_000,
  },
  {
    productName: 'Moonstone Glow',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/moonstone-glow-highlight.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/moonstone-glow-highlight-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/moonstone-glow-highlight.png',
    anchorPoint: 'forehead',
    blendMode: 'screen',
    opacity: 0.4,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { applyToHighPoints: true, shimmerIntensity: 0.6, coolTone: true },
    version: 1,
    fileSizeBytes: 118_000,
  },

  // ═══════════════════════════════════════════════════════════
  // MAKEUP_OVERLAY - Contour (full_face)
  // ═══════════════════════════════════════════════════════════
  {
    productName: 'Light Sculpt Contour',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/light-sculpt-contour.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/light-sculpt-contour-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/light-sculpt-contour.png',
    anchorPoint: 'full_face',
    blendMode: 'multiply',
    opacity: 0.4,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { contourZones: ['jawline', 'cheekbones', 'nose', 'temples'] },
    version: 1,
    fileSizeBytes: 175_000,
  },
  {
    productName: 'Medium Sculpt Contour',
    assetType: 'MAKEUP_OVERLAY',
    modelUrl: 'https://cdn.maikup.app/ar/overlays/medium-sculpt-contour.png',
    textureUrl: 'https://cdn.maikup.app/ar/textures/medium-sculpt-contour-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/medium-sculpt-contour.png',
    anchorPoint: 'full_face',
    blendMode: 'multiply',
    opacity: 0.5,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { contourZones: ['jawline', 'cheekbones', 'nose', 'temples'] },
    version: 1,
    fileSizeBytes: 180_000,
  },

  // ═══════════════════════════════════════════════════════════
  // FACE_MESH - Contour (3D face mesh modification)
  // ═══════════════════════════════════════════════════════════
  {
    productName: 'Light Sculpt Contour',
    assetType: 'FACE_MESH',
    modelUrl: 'https://cdn.maikup.app/ar/models/light-sculpt-contour-mesh.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/light-sculpt-contour-mesh-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/light-sculpt-contour-mesh.png',
    anchorPoint: 'full_face',
    blendMode: 'multiply',
    opacity: 0.3,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { meshType: 'face_contour', displacementStrength: 0.02 },
    version: 1,
    fileSizeBytes: 520_000,
  },
  {
    productName: 'Deep Sculpt Contour',
    assetType: 'FACE_MESH',
    modelUrl: 'https://cdn.maikup.app/ar/models/deep-sculpt-contour-mesh.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/deep-sculpt-contour-mesh-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/deep-sculpt-contour-mesh.png',
    anchorPoint: 'full_face',
    blendMode: 'multiply',
    opacity: 0.35,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { meshType: 'face_contour', displacementStrength: 0.03 },
    version: 1,
    fileSizeBytes: 535_000,
  },

  // ═══════════════════════════════════════════════════════════
  // HAIR_MODEL - Hairstyles (head)
  // ═══════════════════════════════════════════════════════════
  {
    hairstyleName: 'Classic Bob',
    assetType: 'HAIR_MODEL',
    modelUrl: 'https://cdn.maikup.app/ar/models/classic-bob.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/classic-bob-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/classic-bob.png',
    anchorPoint: 'head',
    blendMode: 'normal',
    opacity: 1.0,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { hairPhysics: true, strandCount: 12000, lodLevels: 3 },
    version: 1,
    fileSizeBytes: 2_400_000,
  },
  {
    hairstyleName: 'Beachy Long Waves',
    assetType: 'HAIR_MODEL',
    modelUrl: 'https://cdn.maikup.app/ar/models/beachy-long-waves.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/beachy-long-waves-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/beachy-long-waves.png',
    anchorPoint: 'head',
    blendMode: 'normal',
    opacity: 1.0,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: -1, z: 0 },
    metadata: { hairPhysics: true, strandCount: 18000, lodLevels: 3 },
    version: 1,
    fileSizeBytes: 3_200_000,
  },
  {
    hairstyleName: 'Sleek Low Bun',
    assetType: 'HAIR_MODEL',
    modelUrl: 'https://cdn.maikup.app/ar/models/sleek-low-bun.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/sleek-low-bun-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/sleek-low-bun.png',
    anchorPoint: 'head',
    blendMode: 'normal',
    opacity: 1.0,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 0, z: 0 },
    metadata: { hairPhysics: false, strandCount: 8000, lodLevels: 2 },
    version: 1,
    fileSizeBytes: 1_800_000,
  },

  // ═══════════════════════════════════════════════════════════
  // ACCESSORY_MODEL - Hair Accessories (head)
  // ═══════════════════════════════════════════════════════════
  {
    hairstyleName: 'Claw Clip',
    assetType: 'ACCESSORY_MODEL',
    modelUrl: 'https://cdn.maikup.app/ar/models/claw-clip.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/claw-clip-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/claw-clip.png',
    anchorPoint: 'head',
    blendMode: 'normal',
    opacity: 1.0,
    scale: { x: 0.8, y: 0.8, z: 0.8 },
    offset: { x: 0, y: -5, z: -3 },
    metadata: { materialType: 'tortoiseshell', reflectivity: 0.3 },
    version: 1,
    fileSizeBytes: 650_000,
  },
  {
    hairstyleName: 'Pearl Clip',
    assetType: 'ACCESSORY_MODEL',
    modelUrl: 'https://cdn.maikup.app/ar/models/pearl-clip.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/pearl-clip-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/pearl-clip.png',
    anchorPoint: 'head',
    blendMode: 'normal',
    opacity: 1.0,
    scale: { x: 0.7, y: 0.7, z: 0.7 },
    offset: { x: -4, y: -3, z: 0 },
    metadata: { materialType: 'pearl', reflectivity: 0.6 },
    version: 1,
    fileSizeBytes: 480_000,
  },
  {
    hairstyleName: 'Padded Headband',
    assetType: 'ACCESSORY_MODEL',
    modelUrl: 'https://cdn.maikup.app/ar/models/padded-headband.glb',
    textureUrl: 'https://cdn.maikup.app/ar/textures/padded-headband-diffuse.png',
    thumbnailUrl: 'https://cdn.maikup.app/ar/thumbs/padded-headband.png',
    anchorPoint: 'head',
    blendMode: 'normal',
    opacity: 1.0,
    scale: { x: 1.0, y: 1.0, z: 1.0 },
    offset: { x: 0, y: 2, z: 0 },
    metadata: { materialType: 'fabric', reflectivity: 0.1 },
    version: 1,
    fileSizeBytes: 390_000,
  },
];
